import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/router";

const BookCreate = () => {
  const router = useRouter();
  const [bookTitle, setBookTitle] = useState("");
  const [errors, setErrors] = useState([]);

  async function handleSubmit(e) {
    e.preventDefault();
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/books`,
      {
        method: "POST",
        headers: {
          accept: "application/json",
          "content-type": "application/json",
        },
        body: JSON.stringify({
          title: bookTitle,
        }),
      }
    );

    console.log(res);

    if (res.ok) {
      setErrors([]);
      setBookTitle("");
      return router.push("/libros");
    } else {
      const data = await res.json();
      setErrors(data.errors);
    }
  }

  return (
    <>
      <Head>
        <title>Books App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Create Book</h1>
      {/* <p>{JSON.stringify(errors)}</p> */}
      <form onSubmit={handleSubmit}>
        <input
          onChange={(e) => setBookTitle(e.target.value)}
          value={bookTitle}
          type="text"
        />
        <button>Enviar</button>
        {errors.title && (
          <span style={{ color: "red", display: "block" }}>{errors.title}</span>
        )}
      </form>
      <Link href="/libros">Books List</Link>
    </>
  );
};

export default BookCreate;
