import Head from "next/head";

const BookEdit = () => {
  return (
    <>
      <Head>
        <title>Books App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Book Edit</h1>
    </>
  );
};

export default BookEdit;
